<?php
/**
 * EcomCore Freight Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   EcomCore
 * @package    EcomCore_Freight
 * @author     Thai Phan
 * @copyright  Copyright (c) 2014 EcomCore Pty. Ltd. (http://www.ecomcore.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::helper('eccfreight/address')->isAddressValidationEnabled()): ?>
    <script>
        var addressValidationUrl = '<?php echo $this->getUrl('eccfreight/address/validate'); ?>';
        var eccfreightCountryRegions = <?php echo $this->helper('directory')->getRegionJson(); ?>;
        var addressSuggestTemplate = <?php echo Zend_Json::encode($this->getChildHtml('ecomcore.eccfreight.address.suggestion')); ?>;
        var addressFailureTemplate = <?php echo Zend_Json::encode($this->getChildHtml('ecomcore.eccfreight.address.failure')); ?>;
    </script>
    <script src="<?php echo $this->getSkinUrl('ecomcore/freight/js/opcheckout.js') ?>"></script>
<?php endif ?>
